mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index,name='index'),
    path('article/<int:article_id>',views.article_page,name='article_page'),
    path('edit/<int:article_id>',views.edit_page,name='edit_page'),
    path('edit/action',views.action_page,name='action_page')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls'))
]

mysite/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=10,verbose_name='题目')
    content = models.TextField(verbose_name='内容')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render
from . import models

# Create your views here.
def index(request):
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,'blog/edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request,'blog/edit_page.html',{'article':article})

def action_page(request):
    modefy = request.POST.get('modefy',"MODEFY")
    title = request.POST.get('article_title','ARTICLE_TITLE')
    content = request.POST.get('article_content','ARTICLE_CONTENT')
    if str(modefy) == '0':
        article = models.Article.objects.create(title=title, content=content)
    else:
        article = models.Article.objects.get(pk=modefy)
        article.title = title
        article.content = content
        article.save()
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})

mysite/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<h4>{{article.content}}</h4>
<h5><a href="{% url 'blog:edit_page' article.id %}">修改文章</a></h5>
</body>
</html>

mysite/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_page</title>
</head>
<body>
<form action="{% url 'blog:action_page' %}" method="post">
    {% csrf_token %}
    {% if article %}
        <input type="hidden" name="modefy" value="{{article.id}}">
        <label>
            文章题目<input type="text" name="article_title" value="{{article.title}}">
        </label></br>
        <label>
            文章内容<input type="text" name="article_content" value="{{article.content}}">
        </label></br>
    {% else %}
        <input type="hidden" name="modefy" value="0">
        <label>
            文章题目<input type="text" name="article_title">
        </label></br>
        <label>
            文章内容<input type="text" name="article_content">
        </label></br>
    {% endif %}
    <input type="submit" value="提交">
</form>
</body>
</html>

mysite/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<br>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新建文章</a>
</h1>
</br>
<h2>文章列表</h2>
</br>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a></br>
{% endfor %}
</body>
</html>